services:
  db:
    image: postgres:16.9-alpine3.22
    container_name: gorm
    environment:
      POSTGRES_DB: gorm
      POSTGRES_USER: santi
      POSTGRES_PASSWORD: mysecretpassword
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  backend:
    build: .
    container_name: go_tasks_api
    depends_on:
      - db
    ports:
      - "3000:3000"
    environment:
      PORT: 3000
    volumes:
      - .:/app
    restart: on-failure

volumes:
  pgdata:
  
